### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by kyle-gardner** [BryceLucas/GriZilly#8]
## For each directory, we need a way to write a JSON file filled with metadata for each song in that directory

The JSON files should include 
- [x]  A absolute path to the song file 
- [x]  All of the songs metadata
- [x]  The songs length (its not included in the metadata) (also the length will be in seconds)

The JSON files should be saved in their own folder, named metadata? idk

**Comment by AXBY12** [comment]
I have tried researching this and I honestly have no idea where to start and do not think I would be able to create an outline on how to do this.

**Comment by kyle-gardner** [comment]
Well we already got the metadata from that code you wrote
next step would be to place that metadata into an object, and then after that use that object write a JSON file with the library gson that I added
the picture i put in the discord https://discord.com/channels/1151244287061798962/1165104634512285726/1172685857426251877 shows how to write a JSON file from an object, very easy

**Comment by BryceLucas** [comment]
Yes I like this idea, i can do this as well if no one is already doing it

**Comment by AXBY12** [comment]
sounds good
